name: leonid

services:
  whisper:
    build:
      context: .
      dockerfile: Dockerfile_whisper
    platform: linux/arm64
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL}
      - WHISPER_LANG=${WHISPER_LANG}
    volumes:
      - ${INPUT_DIR:-${AUDIO_DIR}/input}:/data:ro
      - ${OUTPUT_DIR:-${AUDIO_DIR}/output}:/output
      - whisper-cache:/root/.cache/whisper

volumes:
  whisper-cache:
