FROM --platform=linux/arm64 python:3.11-slim-bookworm

ENV PYTHONUNBUFFERED=1 \
    WHISPER_MODEL=base \
    WHISPER_LANG=en \
    WHISPER_OUTPUT_FORMAT=txt

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir openai-whisper

VOLUME ["/data", "/output"]

WORKDIR /app

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
